# Copyright (c) 2023 Larry Aasen. All rights reserved.

name: platforms

defaults:
  run:
    working-directory: example

on:
  workflow_dispatch:

jobs:
  platform-linux:
    strategy:
      matrix:
        runs-on-name: ['ubuntu-latest']
        flutter-version: ['3.7.12']
        device: ['linux']

    runs-on: ${{ matrix.runs-on-name }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter-version }}'
          channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop

      - name: Get flutter packages
        run: flutter pub get

      - name: Run the driver test
        run: 	flutter drive --target=test/driver_test/driver.dart --driver=test/driver_test/driver_test.dart -d ${{ matrix.device }}

      - name: Upload Screenshots to Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: platform-${{ matrix.device }}-${{ matrix.flutter-version }}
          path: example/test/driver_test/screenshots/*

  platform-windows:
    strategy:
      matrix:
        runs-on-name: ['windows-latest']
        flutter-version: ['3.7.12']
        device: ['windows']

    runs-on: ${{ matrix.runs-on-name }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter-version }}'
          channel: 'stable'

      - run: flutter config --enable-windows-desktop

      - name: Get flutter packages
        run: flutter pub get

      - name: Run the driver test
        run: 	flutter drive --target=test/driver_test/driver.dart --driver=test/driver_test/driver_test.dart -d ${{ matrix.device }}

      - name: Upload Screenshots to Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: platform-${{ matrix.device }}-${{ matrix.flutter-version }}
          path: example/test/driver_test/screenshots/*
